add: uiHooks type definition #476
fastify/fastify-swagger pull request #477
Opened 2021-09-23 05:17 UTC by ckcks12

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-09-23 07:08 UTC, climba03003 requested changes
Can you add an unit test for the new types?

2021-09-23 07:08 UTC, climba03003 requested changes

2021-09-23 07:08 UTC, climba03003 commented on index.d.ts
> +  uiHooks: {
It should be optional.
```suggestion
  uiHooks?: {
```

2021-09-23 11:44 UTC, ckcks12 commented
You mean here? 

https://github.com/fastify/fastify-swagger/blob/master/test/types/types.test.ts

2021-09-23 11:45 UTC, climba03003 commented
> 
> 
> You mean here?
> 
> https://github.com/fastify/fastify-swagger/blob/master/test/types/types.test.ts

Yes

2021-09-24 03:49 UTC, ckcks12 commented
done :)

2021-09-24 06:33 UTC, climba03003 approved these changes
LGTM.

2021-09-24 06:38 UTC, merged