feat(openapi): support patternProperties
fastify/fastify-swagger pull request #514
Opened 2021-12-13 16:34 UTC by fxalgrain

#### Description

This PR solve #165 issue. 

The idea is to transform the patternProperties into a valid OpenAPI definition. We lost the precision in public documentation but validation still done on server side  

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-12-13 17:18 UTC, mcollina approved these changes
lgtm

2021-12-13 17:20 UTC, mcollina commented
@climba03003

2021-12-13 17:39 UTC, climba03003 requested changes
Can you also change it on `swagger` side?

2021-12-14 09:21 UTC, fxalgrain commented
I can do it but I m not a daily user of swagger specs. 
Before do it, could you confirm me the following stuff:
It looks like we can apply the same code fix as additionalProperties exists too. https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#schemaObject
And after go in the code, I think we need update the resolveResponse and resolveBodyParams? 

@climba03003  Sounds good for you?

2021-12-14 09:35 UTC, climba03003 commented
> @climba03003 Sounds good for you?

Yes, you can apply the same fix.

2021-12-16 14:05 UTC, fxalgrain commented
@climba03003 I did it, expecting as you wish :)

2021-12-17 06:37 UTC, climba03003 approved these changes
LGTM.

2021-12-17 06:39 UTC, merged