Clone schemas
fastify/fastify-swagger pull request #580
Opened 2022-04-12 15:01 UTC by amit-kleiner

Without the fix the test would have returned a 400 error for the second POST call. This is because running swagger mutates the schema in the global Fastify instance, and breaks the validation. 
This fix clones the schema when we load it in the Fastify swagger package and prevents mutation.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-04-12 15:27 UTC, mcollina approved these changes
lgtm

2022-04-12 15:32 UTC, amit-kleiner commented
fixed lint, thanks!

2022-04-12 15:37 UTC, climba03003 requested changes

2022-04-12 15:40 UTC, amit-kleiner commented on lib/util/common.js
> +      const allSchemas = cloner(instance.getSchemas())
Good question, I copied the package used inside `json-schema-resolver`. 
It only clones the reference object, but doesn't clone the response resolved schema.
Thus the resolved schema contains the original global schema object, which gets mutated.

2022-04-12 15:52 UTC, climba03003 approved these changes
LGTM. Below one just question.

Would it be better if we just clone it once before passing inside json-schema-resolver? I means clone at L38 / L42

2022-04-13 08:01 UTC, amit-kleiner commented
> LGTM. Below one just question.
> 
> Would it be better if we just clone it once before passing inside json-schema-resolver? I means clone at L38 / L42



> LGTM. Below one just question.
> 
> Would it be better if we just clone it once before passing inside json-schema-resolver? I means clone at L38 / L42

It would behave the same. I can move it if you think it's better.
Also, should I bump the version to `5.1.1`?

2022-04-13 08:01 UTC, amit-kleiner commented
> LGTM. Below one just question.
> 
> Would it be better if we just clone it once before passing inside json-schema-resolver? I means clone at L38 / L42



> LGTM. Below one just question.
> 
> Would it be better if we just clone it once before passing inside json-schema-resolver? I means clone at L38 / L42

It would behave the same. I can move it if you think it's better.
Also, should I bump the version to `5.1.1`?

2022-04-13 08:09 UTC, climba03003 commented
> It would behave the same. I can move it if you think it's better. 

Yes, please.

> Also, should I bump the version to `5.1.1`?

I will do the release work, no need to change the version inside this PR.

2022-04-13 08:34 UTC, merged