feat: add support for server relative and templated urls
fastify/fastify-swagger pull request #684
Opened 2022-10-19 10:28 UTC by salvdelpiano

#### Checklist

- [x] run `npm run test` and `npm run benchmark` 
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Hello everyone, in an attempt to fix issues #494 and #540 I integrated support for `server` relative and templated urls.

When `stripBasePath` was set to true then the server url was being parsed as is using `new URL(serverUrl)`. This inevitably resulted in an error when the server url was either relative (e.g. `/foo/bar`) or templated (e.g. `http://localhost:{port}/{basePath}`). 

The changes introduced by this PR solve the issue by first resolving the server url (by replacing templated variables with the corresponing values) and then by using it as is if relative or otherwise parsing it through `new URL(serverUrl)` in order to extract the pathname.

Fixes #494 #540

2022-10-19 11:11 UTC, Uzlopak requested changes
just some remarks and questions

2022-10-19 11:11 UTC, Uzlopak commented on lib/spec/openapi/utils.js
> +    const findVariablesRegex = /{(.*?)}/g // As for OpenAPI v3 spec url variables are named in brackets, e.g. {foo}
I think we can move this variable outside the for loop

2022-10-19 11:11 UTC, Uzlopak commented on lib/spec/openapi/utils.js
> +    for (const match of matches) {
Cant we do and remove lines 95 and 96?

```suggestion
    for (const [variableNameInBrackets, variableName] of matches) {
```

2022-10-19 11:11 UTC, Uzlopak commented on lib/spec/openapi/utils.js
> +      const variableValue = variables?.[variableName]?.default
can we remove the variable-prefix?

variableNameInBrackets => nameInBrackets
variableName => name
variableValue => value

2022-10-19 12:27 UTC, Uzlopak approved these changes
LGTM

2022-10-23 08:35 UTC, Fdawgs requested changes
Does the documentation need updating to account for this feature?

2022-10-23 08:35 UTC, Fdawgs commented on lib/spec/openapi/utils.js
> +        throw new Error(`Server url ${originalUrl} could not be resolved. Make sure to provide a default value for each url variable.`)
```suggestion
        throw new Error(`Server URL ${originalUrl} could not be resolved. Make sure to provide a default value for each URL variable.`)
```

2022-10-23 10:07 UTC, salvdelpiano commented
@Fdawgs Hello there and thank you for the review.

Regarding the documentation I don't think it needs to be updated. This is more of a bug fix and the related behavior was already kind of expected but didn't work properly.

2022-10-23 10:37 UTC, Fdawgs approved these changes

2022-10-23 12:58 UTC, merged

2022-10-23 14:39 UTC, salvdelpiano commented
@Uzlopak thank you for merging this.

I have a small request: I'm participating in hacktoberfest 2022 and it would be very cool to have this PR count toward the monthly PRs goal over there. Is there a chance you can label this PR with the `hacktoberfest-accepted` label?