fix: externalSchemas problem when using openapi (#691)
fastify/fastify-swagger pull request #692
Opened 2022-11-16 17:05 UTC by imjuni

* fix cannot pass externalSchemas when using openapi configuration

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-11-17 16:21 UTC, imjuni commented
@Uzlopak Hi, I add new testcase `external schema reference`.

2022-11-20 14:34 UTC, mcollina approved these changes
lgtm

2022-11-21 15:00 UTC, imjuni commented
is any progress?

2022-11-21 15:26 UTC, Uzlopak requested changes
I am quite hesitant. The PR feels "wrong".
Shouldnt it be also working by using addSchema? Why is there  not a test, that with addSchema also components.schema is set with schemas from addSchema?

Also shouldnt be the test using the "external" schema as reference to prove that it is used internally by this plugin and not only existing in the final openapi definition?

2022-11-21 15:26 UTC, Uzlopak commented on test/spec/openapi/refs.js
> +        200: {
You dont test your change imho. here we need something like { $ref: 'external-schema-01' }

2023-03-08 16:38 UTC, closed without merging