feat: generate path params definition when missing
fastify/fastify-swagger pull request #761
Opened 2023-10-09 14:22 UTC by msebastianb

Generate default param schema only if user doesn't specify a schema for param at all. If there is something, even with missing params, we should not modify it.

**Suggested solution**

- Check for params in the normalized url and for missing params in schema
- Generate a schema from the params found in the url
- Resolve params to the destination format using the previously generated schema
- Apply this behaviour to both specs

Closes https://github.com/fastify/fastify-swagger/issues/750

2023-10-09 16:10 UTC, Eomm requested changes

2023-10-10 07:47 UTC, msebastianb commented on lib/util/generate-params-schema.js
> +      type: paramType(paramName(param))
ok

2023-10-10 07:48 UTC, msebastianb commented on lib/util/generate-params-schema.js
> +  return param ? 'string' : undefined
ok

2023-10-10 07:48 UTC, msebastianb commented on lib/util/match-params.js
> +const paramPattern = /\{[^{}]+\}/g
I didn't find anything useful for this in find-my-way.

2023-10-10 07:48 UTC, msebastianb commented on lib/spec/swagger/utils.js
> +  if (hasParams(url) && (!schema || !schema.params)) {
ok

2023-10-10 07:49 UTC, msebastianb commented on lib/spec/openapi/utils.js
> +  if (hasParams(url) && (!schema || !schema.params)) {
ok

2023-10-10 07:49 UTC, msebastianb commented on lib/spec/swagger/index.js
> +      const swaggerMethod = prepareSwaggerMethod(schema, ref, swaggerObject, url)
ok

2023-10-10 07:51 UTC, msebastianb commented on lib/util/generate-params-schema.js
> +  return schema
good observation

2023-10-10 07:52 UTC, msebastianb commented on lib/util/generate-params-schema.js
> +function generateParamsSchema (url) {
The format is /{userid}. I add it in the description.

2023-10-11 16:22 UTC, Eomm reviewed
- Added few minor suggestions
- [ ] We need documentation

2023-10-11 16:22 UTC, Eomm commented on lib/spec/openapi/utils.js
> +    resolveCommonParams('path', parameters, schema.params, ref, openapiObject.definitions)
It was confusing me as I though we were overwriting the input `schema`

```suggestion
    const schemaGenerated = generateParamsSchema(url)
    resolveCommonParams('path', parameters, schemaGenerated.params, ref, openapiObject.definitions)
```

2023-10-11 16:22 UTC, Eomm commented on lib/util/generate-params-schema.js
> +      type: paramType()
```suggestion
      type: 'string'
```

2023-10-11 16:22 UTC, Eomm commented on lib/util/match-params.js
> +  return matches !== null && matches.length > 0
A bit faster

```suggestion
  return paramPattern.test(url)
```

2023-10-11 17:29 UTC, Uzlopak commented on test/spec/openapi/schema.js
> +  t.same(definedPath.parameters[0], {
Maybe change from `same` to `strictSame`

`same` checks if the object contains keys and values as expected, and if there are more keys it ignores them. 

`strictSame` checks if the object contains only the key and values of the expected object, and throws if there are additional attributes.

2023-10-13 10:45 UTC, simoneb commented
@Eomm , @msebastianb won't be able to keep working on this, can you take care of finishing it up?

2023-10-15 08:08 UTC, mcollina approved these changes
lgtm

This seems done to me. What's missing?

2023-10-15 12:06 UTC, Eomm approved these changes

2023-10-15 12:07 UTC, merged